#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
OUTPUT="$REPO_ROOT/CHANGES-TREE.md"
UPSTREAM="upstream/main"
TMP_FILES="/tmp/vk_changed_files.txt"
TMP_TREE_PY="/tmp/vk_tree.py"
TMP_TABLE_PY="/tmp/vk_table.py"

cd "$REPO_ROOT"

# ── write helper scripts ──────────────────────────────────────────────────────

cat > "$TMP_TREE_PY" << 'EOF'
import sys

lines = [l.strip() for l in sys.stdin if l.strip()]

def build_tree(paths):
    tree = {}
    for path in paths:
        node = tree
        for part in path.split('/'):
            node = node.setdefault(part, {})
    return tree

def render(tree, prefix=''):
    items = sorted(tree.items(), key=lambda x: (bool(x[1]), x[0]))
    out = []
    for i, (name, children) in enumerate(items):
        is_last = i == len(items) - 1
        out.append(f'{prefix}{"└── " if is_last else "├── "}{name}')
        if children:
            out.extend(render(children, prefix + ('    ' if is_last else '│   ')))
    return out

print('.')
for line in render(build_tree(lines)):
    print(line)
EOF

cat > "$TMP_TABLE_PY" << 'EOF'
import sys
from collections import defaultdict

lines = [l.strip() for l in sys.stdin if l.strip()]
groups = defaultdict(int)

for path in lines:
    parts = path.split('/')
    if len(parts) == 1:
        key = '(root)'
    elif parts[0] == 'crates' and len(parts) >= 3 and parts[2] == 'Cargo.toml':
        key = '`crates/*/Cargo.toml`'
    elif len(parts) >= 2:
        key = f'`{parts[0]}/{parts[1]}/`'
    else:
        key = f'`{parts[0]}/`'
    groups[key] += 1

print('| Area | Files |')
print('|------|-------|')
for k, v in sorted(groups.items(), key=lambda x: -x[1]):
    print(f'| {k} | {v} |')
EOF

# ── fetch & collect data ──────────────────────────────────────────────────────

echo "Fetching upstream..."
git fetch upstream --quiet

git diff --name-only "$UPSTREAM"...main | sort > "$TMP_FILES"

FILES_CHANGED=$(wc -l < "$TMP_FILES" | tr -d ' ')
STATS=$(git diff --shortstat "$UPSTREAM"...main)
DATE=$(date '+%Y-%m-%d %H:%M')
TREE=$(python3 "$TMP_TREE_PY" < "$TMP_FILES")
TABLE=$(python3 "$TMP_TABLE_PY" < "$TMP_FILES")

# ── write markdown ────────────────────────────────────────────────────────────

{
  echo "# Changes vs upstream (BloopAI/vibe-kanban)"
  echo ""
  echo "> **${FILES_CHANGED} files changed** — \`${STATS}\`"
  echo "> Last updated: ${DATE}"
  echo ""
  echo "Generated by: \`git diff --name-only upstream/main...main\`"
  echo ""
  echo "---"
  echo ""
  echo "## File tree"
  echo ""
  echo '```'
  echo "$TREE"
  echo '```'
  echo ""
  echo "---"
  echo ""
  echo "## Summary by area"
  echo ""
  echo "$TABLE"
} > "$OUTPUT"

echo "Done → $OUTPUT ($FILES_CHANGED files)"
